import { EnvironmentSchema } from './environment.schema.js';

const {
	TRACKING_DB_URL = 'http://172.20.50.123:9988',
	REDIS_HOST = 'localhost',
	REDIS_PORT = '6379',
	PORT = '7768',
	HOST,
	WHATSAPP_BROWSER_LIFETIME_MINUTES = '15',
	WHATSAPP_BROWSER_VERIFY_LIFE_MINUTES = '5',
	ADB_HOST = 'localhost',
	ADB_PORT = '5037',
	ADB_DEVICE_SERIAL = 'emulator-5554,emulator-5556',
} = process.env;

export const env: EnvironmentSchema = {
	TRACKING_DB_URL,
	REDIS_HOST,
	REDIS_PORT: Number(REDIS_PORT),
	PORT: Number(PORT),
	HOST,
	WHATSAPP_BROWSER_LIFETIME_MINUTES: Number(WHATSAPP_BROWSER_LIFETIME_MINUTES),
	WHATSAPP_BROWSER_VERIFY_LIFE_MINUTES: Number(
		WHATSAPP_BROWSER_VERIFY_LIFE_MINUTES,
	),
	ADB_HOST,
	ADB_PORT: Number(ADB_PORT),
	ADB_DEVICE_SERIAL,
};
